version: '2'
services:
    helper:
        container_name: helper
        build: helper
        ports:
            - 8080:8080
    ui:
        container_name: ui
        build: helper-ui
        ports:
            - 3000:3000
            - 35729:35729
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
        volumes:
            - ./pg-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080